site_name: DOCUMENTACIÓN

theme:
#INIT 
  name: material
#LANGUAGE
  language: es

#FONT LETTER
  font:
    tex: Roboto
    code: Roboto Mono
#COLOR PAGE
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
#EDIT SETTINGS
  features:
    - content.action.edit

#LOGO
  #logo: assets/images/brain.png
  #favicon: images/brain.png


# Extensiones
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Repo Github
repo_url: https://github.com/MarcoJ18/knowledge-hub.io
repo_name: MarcoJ18/knowledge-hub.io

# Edit Page
edit_uri: edit/main/docs/
